# Route configuration
routes:
  - id: route1
    start-seg: seg2
    end-seg: seg6
    path:    
      - seg2
      - seg3
      - seg4
      - seg5
      - seg6
    points:
        - id: point1
        direction: N
    signals:
      - id: signal2
        aspect: Proceed
    conflicts:
      - id: signal8
        aspect: blocked
      - id: signal3
        aspect: blocked
      - id: signal5
        aspect: blocked
      - id: signal9
        aspect: blocked
      - id: signal4
        aspect: blocked
